#
# This workflow will build and run all unit tests using dotnet docker containers,
# each targeting a single version of the dotnet SDK.
#

name: dotnet-pr-docker

on:
  pull_request:
    branches: [ "main", "feature*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-for-dotnet-changes:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.dotnet}}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dotnet:
            - 'dotnet/**'
            - 'samples/dotnet/**'
    - uses: actions/checkout@v3
    # run only if 'dotnet' files were changed
    - name: dotnet changes found
      if: steps.filter.outputs.dotnet == 'true'
      run: echo "dotnet file"
    # run only if not 'dotnet' files were changed
    - name: no dotnet changes found
      if: steps.filter.outputs.dotnet != 'true'
      run: echo "NOT dotnet file"

  build:
    strategy:
        fail-fast: false
        matrix:
          include:
          - { dotnet: '6.0', configuration: Debug, os: ubuntu-latest}
          - { dotnet: '6.0', configuration: Release, os: ubuntu-latest }
          - { dotnet: '7.0', configuration: Release, os: ubuntu-latest }
          - { dotnet: '8.0-preview', configuration: Release, os: ubuntu-latest }

    runs-on: ${{ matrix.os }}
    needs: check-for-dotnet-changes
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
        
    - name: Find solutions
      shell: bash
      if: needs.check-for-dotnet-changes.outputs.output1 == 'true'
      run: echo "solutions=$(find ./ -type f -name "*.sln" | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Pull container dotnet/sdk:${{ matrix.dotnet }}
      if: needs.check-for-dotnet-changes.outputs.output1 == 'true'
      run: docker pull mcr.microsoft.com/dotnet/sdk:${{ matrix.dotnet }}

    - name: Build dotnet solution
      if: needs.check-for-dotnet-changes.outputs.output1 == 'true'
      run: |
        for solution in ${{ env.solutions }}; do
          docker run --rm -v $(pwd):/app -w /app -e GITHUB_ACTIONS='true' mcr.microsoft.com/dotnet/sdk:${{ matrix.dotnet }} /bin/sh -c "dotnet build -c ${{ matrix.configuration }} /warnaserror /app/$solution"
        done
        
    - name: Find unit test projects
      shell: bash
      if: needs.check-for-dotnet-changes.outputs.output1 == 'true'
      run: echo "testprojects=$(find ./dotnet -type f -name "*.UnitTests.csproj" | tr '\n' ' ')" >> $GITHUB_ENV
      
    - name: Run Unit Tests
      if: needs.check-for-dotnet-changes.outputs.output1 == 'true'
      run: |
        for project in ${{ env.testprojects }}; do
          docker run --rm -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/sdk:${{ matrix.dotnet }} /bin/sh -c "dotnet test -c ${{ matrix.configuration }} /app/$project --no-build -v Normal --logger trx"
        done
