name: Python Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "feature*" ]

jobs:
  check-for-python-changes:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.python}}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          python:
            - 'python/**'
    - uses: actions/checkout@v3
    # run only if 'python' files were changed
    - name: python changes found
      if: steps.filter.outputs.python == 'true'
      run: echo "Python file"
    # run only if not 'python' files were changed
    - name: no python changes found
      if: steps.filter.outputs.python != 'true'
      run: echo "NOT python file"

  python-unit-tests:
    runs-on: ${{ matrix.os }}
    needs: check-for-python-changes
    if: needs.check-for-python-changes.outputs.output1 == 'true'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install poetry pytest
        cd python
        poetry install --without chromadb --without hugging_face
    - name: Test with pytest
      run: |
        cd python && poetry run pytest ./tests/unit
